language: php
<<<<<<< HEAD
<<<<<<< HEAD

=======
>>>>>>> upstream/master
=======
>>>>>>> upstream/master
php:
    - 5.4
    - 5.5
    - 5.6
<<<<<<< HEAD
<<<<<<< HEAD
    #- hhvm
    - nightly
    - "7.0"



sudo: false



git:
    submodules: false



addons:
    apt:
        packages:
            #- php-codesniffer
            #- phpmd
            #- shellcheck
=======
    - "7.0"
    - hhvm
    - nightly
>>>>>>> upstream/master
=======
    - "7.0"
    - hhvm
    - nightly
>>>>>>> upstream/master



matrix:
    allow_failures:
<<<<<<< HEAD
<<<<<<< HEAD
=======
        - php: hhvm
>>>>>>> upstream/master
=======
        - php: hhvm
>>>>>>> upstream/master
        - php: nightly



before_script:
<<<<<<< HEAD
<<<<<<< HEAD

=======
>>>>>>> upstream/master
=======
>>>>>>> upstream/master
    # Store all files in your own bin
    - mkdir bin
    - export PATH=$PATH:$PWD/bin/

<<<<<<< HEAD
<<<<<<< HEAD

    # Install validation tools
    # - npm install -g htmlhint csslint jshint jscs jsonlint js-yaml html-minifier@0.8.0 clean-css uglify-js
    - npm install -g htmlhint csslint jsonlint js-yaml html-minifier@0.8.0 clean-css
    
=======
>>>>>>> upstream/master
=======
>>>>>>> upstream/master
    # Install phpcs
    - curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
    - install --mode 0755 phpcs.phar $PWD/bin/phpcs

<<<<<<< HEAD
<<<<<<< HEAD
    # Install phpmd
    - wget --no-check-certificate -c http://static.phpmd.org/php/latest/phpmd.phar
    - install --mode 0755 phpmd.phar $PWD/bin/phpmd
    
    # Download dbwebb-validate
    - wget -O dbwebb-validate https://raw.githubusercontent.com/mosbth/dbwebb-cli/master/dbwebb2-validate
    - install --mode 0755 dbwebb-validate $PWD/bin/dbwebb-validate

    # Create a build directory for output
    - mkdir build



script:
    # Check versions of validation tools
    - node --version
    - npm --version
    
    - htmlhint --version
    - csslint --version
    #- jscs --version
    #- jshint --version
    - phpcs --version
    - phpmd --version
    #- jsonlint --version
    - js-yaml --version
    #- shellcheck --version
    
    - html-minifier --version
    - cleancss --version
    #- uglifyjs --version
    
    # Run validation & publish
    - dbwebb-validate --version
    - dbwebb-validate --check
    - dbwebb-validate --publish --publish-to build/ example/
=======
=======
>>>>>>> upstream/master
    #- wget http://getcomposer.org/composer.phar
    #- php composer.phar install --no-interaction
    - wget https://scrutinizer-ci.com/ocular.phar

    # Composer
    - composer validate
    - composer update


script: 
    - php --version
    - phpcs --version
    - composer --version
    - phpunit --version

    - mkdir -p build/logs
    - phpunit --bootstrap test/config.php --coverage-clover build/logs/clover.xml test
    - make test



after_script:
    - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
<<<<<<< HEAD
>>>>>>> upstream/master
=======
>>>>>>> upstream/master



notifications:
    irc: "irc.freenode.org#dbwebb"
<<<<<<< HEAD
<<<<<<< HEAD

    webhooks:
        urls:
            - https://webhooks.gitter.im/e/fdbd27d2391724c0231b

        # options: [always|never|change] default: always
        on_success: change
        on_failure: always
        on_start: never
=======
=======
>>>>>>> upstream/master
    webhooks:
        urls:
          - https://webhooks.gitter.im/e/86877cd2fec2eb37da31
        on_success: change  # options: [always|never|change] default: always
        on_failure: always  # options: [always|never|change] default: always
        on_start: never     # options: [always|never|change] default: always
<<<<<<< HEAD
>>>>>>> upstream/master
=======
>>>>>>> upstream/master
